### ISSUE TITLE
Vk.com is broken... again. FeelsBadMan

### ISSUE THREAD

**Issue by Kenalfy** [Wykks/Untamed-Now-Playing-Next#114]
Other sites works normally. Just when i tried to use it with vk.com file don't renews.
I tried to restard firefox and reinstall plugin but it wont work

**Comment by Senpos** [comment]
Answered already in #113.
If you can't build / sign dev extension by yourself, i can post dev one, but i need approval from @Wykks.

**Comment by Wykks** [comment]
Mozilla just reviewed the last version (which contains vk.com fix). Buuut it didn't pass review, because :-1:

"AngularJS 1.x is considered highly insecure for add-on code and will only be allowed until the end of September. We strongly recommend using another framework. We accepts only latest version."

Well... I'll get rid of angular 1.x then !

@Senpos Yup you totally can

**Comment by Senpos** [comment]
@Kenalfy Here the latest version of extension where **new Vk.com** is working fine.
 [Download](https://docs.google.com/uc?id=0B6HBCntn0EZRMU4wZ3hrNGJYcTg)

Note, it is not official version, i've built it  from latest git development branch, but it should work fine, i believe.

Due to signing process, some meta-data could be wrong in this build, so i claim, that all right are going to extension's initial developers! 

I'd recommend you to upgrade to official version once it will release!

**Comment by Kenalfy** [comment]
thanks man :D really appreciate

**Comment by Wykks** [comment]
aaand it's released :)
(last version accepted with angular 1.x though..)
