### ISSUE TITLE
Jombly Support

### ISSUE THREAD

**Issue by jasperdanan** [Wykks/Untamed-Now-Playing-Next#127]
Thanks for your hard work! 
Jombly: K-pop Radio | http://www.jombly.com/

**Comment by Senpos** [comment]
@Wykks 
Here are some code i tried to play with: [jombly.js](https://gist.github.com/Senpos/f2a54eefb64c09243de2d1cdfe2231fa)
and **index.js** line
`createMusicWebsiteWorker('*.jombly.com', 'jombly.js', 'top');`

Works for me in console, but for some reason couldn't make it work as extension. Here what i've got as [result](http://i.imgur.com/SdJXp4H.png).

Probably, i'm missing something, hope you'll clear the situation :)

**Comment by Wykks** [comment]
![image](https://cloud.githubusercontent.com/assets/1236069/23141893/4519178c-f7b9-11e6-9b55-12318d72c156.png)
(Firefox developer edition using about:debugging#addons )
You cannot use `this.selector` inside `isPlaying`, that's why `isPlaying` is above `findSelector` is other files.
I know it's weird, I totally should improve this :D (#94)
