### ISSUE TITLE
UNP fails to create text and jpg files

### ISSUE THREAD

**Issue by paolobellan** [Wykks/Untamed-Now-Playing-Next#154]
that's pretty much it... i don't know why....

**Comment by Senpos** [comment]
What is the path you are trying to save files to? Make sure that Firefox has rights to write data there. I chose non-system drive to save files from UNP usually and it worked just fine.

**Comment by Wykks** [comment]
You should have an error message when you save UNP options, or UNP have issues with the music website your using. Can you test with others websites ?

**Comment by drsgfire** [comment]
I am having issues with music streaming from SoundCloud like this. To test if it was just SoundCloud I went to test it with Pandora and it still was not creating a txt file or the album image.

So I made a txt file with the same name represented in UNP's options in the folder I specified and the next song that played through Pandora populated the correct info and the correct artwork.

I then went back to test some things on SoundCloud but I can't get it to work. I thought maybe turning desktop notifications on would help because it seemed like the Pandora site desktop notifications were syncing up with exactly when the files would populate the new data but unfortunately it did not.

Any ideas on this?

**Comment by Senpos** [comment]
@drsgfire What version of extension do you use? Fixed SoundCloud and Pandroda support is avaliable in the latest one which is not in "**Mozilla Add-ons**" site yet.

**Comment by drsgfire** [comment]
@Senpos Hey, thanks for the forward. I downloaded the developer version of Firefox and tried the 4.5 (Which directly addresses the SoundCloud issue... lol) and it is working great. Sorry I noobed out there and didn't check that before. Thanks for the help.
