### ISSUE TITLE
Pandora song title triples up when the song title scrolls on site

### ISSUE THREAD

**Issue by ACMerriman** [Wykks/Untamed-Now-Playing-Next#161]
If a song title is too long to fit in the space provided on Pandora, it has the song title scroll. When UNP is grabbing the song title, it grabs it 3 times. I was able to fix it by having the track selector in pandora.js look at the track name in the footer (critical lines below), but I'm sure a more elegant solution is possible

`this.selector2 = $('div.Tuner__Audio__TrackDetail__labels');`
`this.trackSelector = this.selector2.find('a[data-qa=mini_track_title]');`

This method has the added bonus of getting the track name faster than the method you used

**Comment by Senpos** [comment]
@ACMerriman 
Thanks for creating an issue.

Here is a [test branch](https://github.com/Senpos/Untamed-Now-Playing-Next/tree/iss-161) where i changed almost all things to be grabbed from the _bottom panel_, except **Album Name**, since there is no that one.

Also, i'm [attaching an XPI](https://drive.google.com/uc?id=0B6HBCntn0EZRYzlDTjVaOV91SW8) with new modifications included, so you can test if it any better.

**Comment by ACMerriman** [comment]
works great. Can't wait for the official release so I don;t have to keep installing it every time I open Firefox

**Comment by Senpos** [comment]
@ACMerriman Since Mozilla is going to make all extension creators move to new WebExtension format for FF57 huge release, i am not sure if it is actually possible to publish new version of UNPN to the store. 

But i have solution for you to make life easier and stop installing extension every time browser is openned:

1. Install [Firefox Developer Edition](https://www.mozilla.org/ru/firefox/developer/)
2. Open it, go to the `about:config`, accept to the things described in that window
3. Find `xpinstall.signatures.required` entry through the search field and set **False** by double-clicking on it

You are done. Now you can simply open **Add-ons** page in your browser and _drag-and-drop_ **even unsigned extension**. No annoying things will happen again.

_Firefox Developer Edition_ is like a bit **beta** one, but still working great and capable for things like this.
