### ISSUE TITLE
UNP doesn't write a file to my selected directory

### ISSUE THREAD

**Issue by Dylan-Thorp** [Wykks/Untamed-Now-Playing-Next#183]
I am using Waterfox 56.2.6 and I am using UNP 4.7.1, I set my directory to a twitch folder located on my desktop and when I started playing songs on my pandora it didn't write any txt file. I have tried closing the browser and reopening it in hopes of getting it to work, however it hasn't. I have also closed pandora and reopened it but to no avail.

**Comment by Senpos** [comment]
Hey @Dylan-Thorp,

I fixed the problem with Pandora and will release it soon, but there's a problem with album arts. Often, Pandora updates arts **way** later then the core information, like artist name or track name, so UNP may pickup old art and use it for new song. So I am not sure what to do - remove album art feature for Pandora at all or leave it as is. 

Since nobody else except you reported about the problem with Pandora so far, you may be the only person who is interested in Pandora support, so let me know what you think.

**Comment by Senpos** [comment]
Hey, I managed to fix the problem without quirks described above, but **album name** for Pandora is gone now, unfortunately.

**Comment by Senpos** [comment]
[version 4.7.2 ](https://github.com/Wykks/Untamed-Now-Playing-Next/releases/tag/4.7.2)with fix for this released, please, check it

**Comment by Dylan-Thorp** [comment]
Thank you
