### ISSUE TITLE
Save button not working in settings page

### ISSUE THREAD

**Issue by ImQreative** [Wykks/Untamed-Now-Playing-Next#37]
I am having an issue where the save button on the settings page not working.
I fill in the required information but when I click save, the button graphic changes to being depressed and never saves.              No loading starts or anything, this is all I see until I refresh the page:
![save button](https://cloud.githubusercontent.com/assets/12002397/7213588/d8f8922e-e538-11e4-913c-3656c4b16cf9.JPG)

I have tried a few different directories and none of them have yielded any different outcome...

**Comment by Wykks** [comment]
It's because of NPAPI decrecation. See #7 
Unfortunately, I can't do much about it.

I could port UNPN to Firefox, but it would just duplicate [this extension](https://obsproject.com/forum/resources/currentsong.182/).
What do you guys thinks ?

**Comment by ImQreative** [comment]
Yeah, I think porting it ro FF would be beneficial to alot of people

**Comment by 5trick3n** [comment]
Yes, Please port to firefox! I used this for about a day as part of my rainmeter setup, then it stopped working (probably due to NPAPI deprecation). The extension doesn't support last.fm, which is a deal breaker for me. An extension with all the sites supported that UNPN does would be a big hit in the rainmeter community!

**Comment by Wykks** [comment]
Alright, I started the port !
It's Harder than I thought as I know almost nothing about Firefox addon.
But It should be fine. I'll post something this week-end.
