### ISSUE TITLE
Question, chrome extension

### ISSUE THREAD

**Issue by Dethrail** [Wykks/Untamed-Now-Playing-Next#60]
Can we expect Chrome extension, and how soon?
I could not run it in chrome, maybe I did something wrong?

**Comment by Wykks** [comment]
UNP doesn't work on Chrome anymore because of NPAPI deprecation by Chrome.
Works are ongoing to see if it's feasible to make a new version for chrome. But it's a bit tricky.
More information here : https://github.com/Wykks/Untamed-Now-Playing-Next/issues/40
Anything can happen.
It just depends on if I (or someone else) want to borrow some time for this.

**Comment by Fanoman** [comment]
I enabled NPAPI in chrome://flags and turned off auto-update. Kind of solution for some amount of time. Almost working fine except one thing - "Integrate with Nightbot?". What is can be wrong? Just can't save  after I entered my username and API.

**Comment by Wykks** [comment]
Google is going to remove NPAPI support completly this month (https://www.chromium.org/developers/npapi-deprecation)
It's about a couple of week now .. :(

About the nightbot stuff, I'm not surprised. The last commit about nightbot (by Night itself) is from Apr 2014.
Nobody told me anything about it since now...
I can work on Nightbot integration on the Firefox version if you want :)
(But can't guarantee when...)

About the Chrome version, we found a way to do it. What's blocking ? Time, time and time

**Comment by Fanoman** [comment]
Maybe for someone else. I will stick with Chrome :)

**Comment by Wykks** [comment]
see #93
