### ISSUE TITLE
Add options button to Extensions Manager on Firefox

### ISSUE THREAD

**Issue by SW1FT** [Wykks/Untamed-Now-Playing-Next#71]
![options button pls](https://cloud.githubusercontent.com/assets/6627739/11005668/febf62ee-84b6-11e5-9ee4-7dccb8b9bbdf.png)

**Comment by Wykks** [comment]
Yes I already considered this but I'm using the Add-on SDK exclusively (https://developer.mozilla.org/en-US/Add-ons/SDK) in order to avoid any deprecation (or less...).
The only way to do this with the SDK is by using `simple-prefs` (https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-prefs) which cannot be used in UNP.

There a workaround: a button made with `simple-prefs` which open the setting page of UNP. This way you have to click 2 times from the Extensions Manager to get the settings. Is that fine for you ?

**Comment by SW1FT** [comment]
Yeah, it's fine, thanks!

**Comment by Wykks** [comment]
Dooone !

**Comment by SW1FT** [comment]
Awesome, thank you!
