### ISSUE TITLE
any new on a chrome extention

### ISSUE THREAD

**Issue by chazragg** [Wykks/Untamed-Now-Playing-Next#93]
i understand that you are having trouble with making a chrome extension as there is no way to write a file from an extention to out HDD with chrome but i was wondering how the progression is going 

if it is any help https://github.com/pendo324/EssentialNowPlaying this tool managed to do it but i believe they use programs installed on out machieans in order to save and dispaly the text

**Comment by Wykks** [comment]
Hi !

Sorry for the late response, I disconnected from internet for about 15 days

I know EssentialNowPlaying, and yes they have made an external program to save the files. I prefer to not do that because it require to launch something else, not just the browser.

I recently moved UNP to AngularJS, and made it so everything inside the "common" directory is now totally independant of Firefox.
Basically, the main task to do now for chrome is about finding a good way to write a file with an extension.
https://github.com/Wykks/Untamed-Now-Playing-Next/issues/40
Here we talk about a way to do this. CuGBabyBeaR made this : 
https://github.com/CuGBabyBeaR/UNPPlayground

But it was 10 month ago, things are changing theses days with WebExtensions; Firefox/Chrome are already compatible with this API. And Firefox will drop their Add-on SDK (which is currently used in UNP to write files).

Until a solution show up for writing files with WebExtensions, I don't think I will do anything about making a Chrome extension.
https://webextensions.uservoice.com/forums/315663-webextension-api-ideas/suggestions/9438246-support-os-file-or-at-least-chrome-filesystem

**Comment by ioRekz** [comment]
Hello, I would like to make a chrome extension that send the current song to a webservice. It looks like the only pain point is to write to a file and I would not need it.

In that case, what need to be done or changed to port this plugin to chrome.  thanks !

**Comment by Wykks** [comment]
Hi !

As I said above : 
> I recently moved UNP to AngularJS, and made it so everything inside the "common" directory is now totally independant of Firefox.

So in theory you should be able to use everything inside the directory `data/common/` (or just `data/common/websites-support`) and also adapt `browserFunc.js` for chrome (which is used to communicate beetween pages workers and the extension itself).

But as of today, there is still some code inside `lib/nowPlayingIO.js` not only related to writing files (eg: `processNPVar` func, which replace %s%,...).

I can separate the `data/common/` directory in another repo, in order to make it easier for you to keep your extension up to date :)

Good luck !

**Comment by ioRekz** [comment]
Thanks for the detailed explanation.
Sure having a separate repo would help a lot but doing it just for me could be overkill.

To tell more about my project : I just released www.songq.tv, a free music player for streamers with overlay customization.  (it's using React)

I guess the most important part for me will be the websites-support code.

**Comment by Wykks** [comment]
Very interesting :) 
I indent to separate the common directory anyway, when I'll revive the chrome extension ... Someday :smile: 

Bay the way, just so you know, websites-support are unit tested here : 

https://github.com/Wykks/UNP-tests

(Only 11 websites tested for now, but better than nothing !)

**Comment by ioRekz** [comment]
Great ! hope Ill be able to add more tests on the occasion

**Comment by chazragg** [comment]
i hate to bring up an old thread but do you think there is any way to use the download API for google chrome so you create a file that we download to out drives rather than trying to create the file straight to the hard disk ?

**Comment by Wykks** [comment]
Yeah it should works, but, this way, it will ask the user everytime the song changes (or spam the download section of chrome when the setting is set to "don't ask when downloading a file")... Not good

**Comment by chazragg** [comment]
fair point suppose only real way is a 3rd party program. maybe a plugin for OBS that talks to your extension ? that way it keeps it more together

**Comment by Wykks** [comment]
An OBS plugin could work, but UNP can be used with something else than OBS

**Comment by buffet-time** [comment]
any news

**Comment by Wykks** [comment]
No sorry, even UNP for Firefox is not in good shape for the future since Firefox is going to drop the SDK which UNP rely on...
I think I'll have to create an external software to write the file...
